// Auto-generated TypeScript definitions from OpenAPI specification
// Do not edit this file manually
//
// To regenerate this file, run: npm run docs:export-types
// Note: Requires valid openapi.yaml

// ========== Data Models ==========

/**
 * Agent represents an AI agent in the system
 */
export interface Agent {
  id: string;
  name: string;
  description?: string;
  apiKey?: string;
  apiSecret?: string;
  createdAt: string;
  updatedAt?: string;
}

/**
 * Authentication tokens response
 */
export interface AuthTokens {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
}

// ========== API Endpoints ==========

// ========== Common Types ==========

/**
 * Pagination metadata
 */
export interface PaginationMeta {
  page: number;
  perPage: number;
  total: number;
  totalPages: number;
}

/**
 * Standard API response wrapper
 */
export interface APIResponse<T = any> {
  success: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
    details?: any;
  };
  meta?: PaginationMeta;
}

